"""Initial schema

Revision ID: 267e42c5aefa
Revises: 
Create Date: 2026-01-08 20:09:38.526068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '267e42c5aefa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibrations',
    sa.Column('svo2_file_path', sa.Text(), nullable=False),
    sa.Column('fx', sa.Float(), nullable=False),
    sa.Column('fy', sa.Float(), nullable=False),
    sa.Column('cx', sa.Float(), nullable=False),
    sa.Column('cy', sa.Float(), nullable=False),
    sa.Column('baseline', sa.Float(), nullable=False),
    sa.Column('distortion_coeffs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calibration_matrix', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rectification_matrix', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('projection_matrix_left', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('projection_matrix_right', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=False),
    sa.Column('image_height', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('svo2_file_path')
    )
    op.create_table('job_configs',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('sam3_model_variant', sa.String(length=50), nullable=False),
    sa.Column('sam3_confidence_threshold', sa.Float(), nullable=False),
    sa.Column('sam3_iou_threshold', sa.Float(), nullable=False),
    sa.Column('sam3_batch_size', sa.Integer(), nullable=False),
    sa.Column('frame_skip', sa.Integer(), nullable=False),
    sa.Column('enable_tracking', sa.Boolean(), nullable=False),
    sa.Column('export_3d_data', sa.Boolean(), nullable=False),
    sa.Column('object_class_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('object_classes',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('kitti_type', sa.String(length=50), nullable=True),
    sa.Column('is_preset', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('presets',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('processing_jobs',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_stage', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('input_paths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_directory', sa.Text(), nullable=True),
    sa.Column('config_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_stage', sa.Integer(), nullable=True),
    sa.Column('total_frames', sa.Integer(), nullable=True),
    sa.Column('processed_frames', sa.Integer(), nullable=True),
    sa.Column('total_detections', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['job_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_status'), 'processing_jobs', ['status'], unique=False)
    op.create_table('exports',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('output_path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exports_job_id'), 'exports', ['job_id'], unique=False)
    op.create_table('frames',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('svo2_file_path', sa.Text(), nullable=False),
    sa.Column('svo2_frame_index', sa.Integer(), nullable=False),
    sa.Column('timestamp_ns', sa.BigInteger(), nullable=False),
    sa.Column('timestamp_relative_ms', sa.Float(), nullable=False),
    sa.Column('image_left_path', sa.Text(), nullable=True),
    sa.Column('image_right_path', sa.Text(), nullable=True),
    sa.Column('depth_path', sa.Text(), nullable=True),
    sa.Column('point_cloud_path', sa.Text(), nullable=True),
    sa.Column('extraction_status', sa.String(length=20), nullable=False),
    sa.Column('segmentation_status', sa.String(length=20), nullable=False),
    sa.Column('reconstruction_status', sa.String(length=20), nullable=False),
    sa.Column('sequence_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frames_job_id'), 'frames', ['job_id'], unique=False)
    op.create_index(op.f('ix_frames_svo2_file_path'), 'frames', ['svo2_file_path'], unique=False)
    op.create_table('frame_metadata',
    sa.Column('frame_id', sa.UUID(), nullable=False),
    sa.Column('accel_x', sa.Float(), nullable=True),
    sa.Column('accel_y', sa.Float(), nullable=True),
    sa.Column('accel_z', sa.Float(), nullable=True),
    sa.Column('gyro_x', sa.Float(), nullable=True),
    sa.Column('gyro_y', sa.Float(), nullable=True),
    sa.Column('gyro_z', sa.Float(), nullable=True),
    sa.Column('orientation_w', sa.Float(), nullable=True),
    sa.Column('orientation_x', sa.Float(), nullable=True),
    sa.Column('orientation_y', sa.Float(), nullable=True),
    sa.Column('orientation_z', sa.Float(), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.Column('extended_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['frame_id'], ['frames.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('frame_id')
    )
    op.create_table('tracks',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('object_class_id', sa.UUID(), nullable=False),
    sa.Column('first_frame_id', sa.UUID(), nullable=False),
    sa.Column('last_frame_id', sa.UUID(), nullable=False),
    sa.Column('frame_count', sa.Integer(), nullable=False),
    sa.Column('avg_confidence', sa.Float(), nullable=True),
    sa.Column('max_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['first_frame_id'], ['frames.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_frame_id'], ['frames.id'], ),
    sa.ForeignKeyConstraint(['object_class_id'], ['object_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracks_job_id'), 'tracks', ['job_id'], unique=False)
    op.create_table('annotations',
    sa.Column('frame_id', sa.UUID(), nullable=False),
    sa.Column('object_class_id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=True),
    sa.Column('bbox_2d_x', sa.Float(), nullable=False),
    sa.Column('bbox_2d_y', sa.Float(), nullable=False),
    sa.Column('bbox_2d_width', sa.Float(), nullable=False),
    sa.Column('bbox_2d_height', sa.Float(), nullable=False),
    sa.Column('bbox_3d_x', sa.Float(), nullable=True),
    sa.Column('bbox_3d_y', sa.Float(), nullable=True),
    sa.Column('bbox_3d_z', sa.Float(), nullable=True),
    sa.Column('bbox_3d_length', sa.Float(), nullable=True),
    sa.Column('bbox_3d_width', sa.Float(), nullable=True),
    sa.Column('bbox_3d_height', sa.Float(), nullable=True),
    sa.Column('bbox_3d_rotation_y', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('mask_area', sa.Integer(), nullable=True),
    sa.Column('point_count', sa.Integer(), nullable=True),
    sa.Column('truncation', sa.Float(), nullable=False),
    sa.Column('occlusion', sa.Integer(), nullable=False),
    sa.Column('alpha', sa.Float(), nullable=True),
    sa.Column('mask_path', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['frame_id'], ['frames.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['object_class_id'], ['object_classes.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotations_frame_id'), 'annotations', ['frame_id'], unique=False)
    op.create_index(op.f('ix_annotations_track_id'), 'annotations', ['track_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotations_track_id'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_frame_id'), table_name='annotations')
    op.drop_table('annotations')
    op.drop_index(op.f('ix_tracks_job_id'), table_name='tracks')
    op.drop_table('tracks')
    op.drop_table('frame_metadata')
    op.drop_index(op.f('ix_frames_svo2_file_path'), table_name='frames')
    op.drop_index(op.f('ix_frames_job_id'), table_name='frames')
    op.drop_table('frames')
    op.drop_index(op.f('ix_exports_job_id'), table_name='exports')
    op.drop_table('exports')
    op.drop_index(op.f('ix_processing_jobs_status'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_table('presets')
    op.drop_table('object_classes')
    op.drop_table('job_configs')
    op.drop_table('calibrations')
    # ### end Alembic commands ###
